openapi: 3.0.0
info:
  title: Common Fate Remote Configuration
  version: "1.0"
  contact:
    name: Common Fate
    url: "https://commonfate.io"
  description: "An API for loading deployment configuration, such as notifications settings."
servers:
  - url: "http://localhost:6565"
paths:
  /api/v1/config:
    get:
      summary: Get Deployment Configuration
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/DeploymentConfigResponse"
      operationId: get-config
      description: Get deployment configuration.
components:
  schemas:
    DeploymentConfiguration:
      title: DeploymentConfiguration
      x-stoplight:
        id: i1tvp3xdvhkcd
      type: object
      description: The configuration for a Common Fate deployment.
      properties:
        notificationsConfiguration:
          $ref: "#/components/schemas/NotificationsConfiguration"
      required:
        - notificationsConfiguration
    NotificationsConfiguration:
      title: NotificationsConfiguration
      x-stoplight:
        id: rnaw9z0bzz24m
      type: object
      description: Notifications configuration for the deployment.
      properties:
        slack:
          $ref: "#/components/schemas/SlackConfiguration"
        slackIncomingWebhooks:
          type: object
          x-go-type: "map[string]map[string]string"
    SlackConfiguration:
      title: SlackConfiguration
      x-stoplight:
        id: eqg2pz843590a
      type: object
      properties:
        apiToken:
          type: string
          description: "The Slack API token. Should be a reference to secret in `awsssm://` format."
      required:
        - apiToken
      description: The Slack notification configuration.
  responses:
    DeploymentConfigResponse:
      description: The configuration of this Common Fate deployment.
      content:
        application/json:
          schema:
            properties:
              deploymentConfiguration:
                $ref: "#/components/schemas/DeploymentConfiguration"
            required:
              - deploymentConfiguration
  requestBodies:
