package: types
generate:
  chi-server: true
  models: true
  embedded-spec: true
  client: true
output-options:
  skip-prune: true
import-mapping:
  ./accesshandler/openapi.yml: github.com/common-fate/common-fate/accesshandler/pkg/types
output: pkg/types/api.gen.go
