openapi: 3.0.0
info:
  title: Deployment CLI
  version: '1.0'
  contact:
    name: Common Fate
    url: 'https://commonfate.io'
  description: Deployment CLI
servers:
  - url: 'http://localhost:9000'
paths:
  /api/v1/providers:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/ListProvidersResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: list-providers
  /api/v1/registry/providers:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/ListRegistryProvidersResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: list-registry-providers
components:
  responses:
    ErrorResponse:
      description: An error returned from the API.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
          examples: {}
    ListRegistryProvidersResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              next:
                type: string
                nullable: true
              providers:
                type: array
                items:
                  $ref: '#/components/schemas/RegistryProvider'
            required:
              - next
              - providers
    ListProvidersResponse:
      description: Providers registered in the Common Fate deployment
      content:
        application/json:
          schema:
            type: object
            properties:
              next:
                type: string
                nullable: true
              providers:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
            required:
              - next
              - providers
  schemas:
    RegistryProvider:
      title: RegistryProvider
      x-stoplight:
        id: nhwc8ubm2f7wa
      type: object
      properties:
        team:
          type: string
        name:
          type: string
        version:
          type: string
      required:
        - team
        - name
        - version
    Provider:
      title: Provider
      x-stoplight:
        id: iujnfevm5byx0
      type: object
      properties:
        team:
          type: string
        name:
          type: string
        version:
          type: string
        alias:
          type: string
        id:
          type: string
      required:
        - team
        - name
        - version
        - alias
        - id
tags:
  - name: grants
  - name: runtime
