openapi: 3.0.0
info:
  title: Example API
  version: '1.0'
  contact:
    name: Common Fate
    url: 'https://commonfate.io'
  description: Example API
servers:
  - url: 'http://localhost:9000'
paths:
  /api/v1/secrets:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-secret
    post:
      summary: ''
      operationId: post-secret
      responses:
        '200':
          description: OK
  /api/v1/deployments:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-deployment
    post:
      summary: ''
      operationId: post-deployment
      responses:
        '200':
          description: OK
components:
  responses:
    ErrorResponse:
      description: An error returned from the API.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
          examples: {}
tags:
  - name: grants
  - name: runtime
