openapi: 3.0.0
info:
  title: Example API
  version: "1.0"
  contact:
    name: Common Fate
    url: "https://commonfate.io"
  description: Example API
servers:
  - url: "http://localhost:9000"
paths:
  /api/v1/secrets:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        "200":
          description: OK
      operationId: get-secret
    post:
      summary: ""
      operationId: post-secret
      responses:
        "200":
          description: OK
  /api/v1/deployments:
    post:
      summary: ""
      operationId: post-deployment
      responses:
        "200":
          $ref: "#/components/responses/DeploymentResponse"
      description: Create or update a deploymen
      requestBody:
        $ref: "#/components/requestBodies/DeploymentRequest"
components:
  responses:
    ErrorResponse:
      description: An error returned from the API.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
          examples: {}
    DeploymentResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              stackId:
                type: string
            required:
              - stackId
  requestBodies:
    DeploymentRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              stackId:
                type: string
              team:
                type: string
              name:
                type: string
              version:
                type: string
            required:
              - team
              - name
              - version
tags:
  - name: grants
  - name: runtime
